from . import process
from . import activity
from . import location
from . import department
from . import account_payment
from . import account_move
from . import account_asset
from . import res_partner_bank
from . import activity_location
